# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "konstantin-zubarev/centos-repo"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end
  
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.define "centos" do |centos|
    centos.vm.network "private_network", type: "dhcp"
    centos.vm.hostname = "centos-repo"
    centos.vm.provider :virtualbox do |virtualbox|
      virtualbox.name = "centos-repo"
    end
  end
end
